[build]
command = "npm run build"
publish = "/build"
base = "/"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[[plugins]]
package = "@netlify/plugin-functions-install-core"

[build.environment]
NETLIFY_NEXT_PLUGIN_SKIP = "true"
